languageCode = "en"
languageName = "English"
weight = 1
title = "Jack Case"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[author]
name = "Jack Case"
image = "img/blowfish_logo.png"
headline = "Computer engineer, Jack of all trades"
bio = "A little bit about you"
links = [ 
  { email = "mailto:jackacase+portfolio@gmail.com" }, 
  { github = "https://github.com/GandalfDG" },
  { linkedin = "https://www.linkedin.com/in/jackacase/"},
  { mastodon = "https://indieweb.social/@GandalfDG" } ]
